// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_aJPhXEvrbkds9_JGYWbghdpX5qLaVDA',
    appId: '1:143272886853:android:d60b3a56ef17648f5cd92c',
    messagingSenderId: '143272886853',
    projectId: 'janari0-b4e82',
    databaseURL: 'https://janari0-b4e82-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'janari0-b4e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-QNrBxlX4vsnah_NkXT2N9Ary4Xwi-fs',
    appId: '1:143272886853:ios:19056645c00bc1545cd92c',
    messagingSenderId: '143272886853',
    projectId: 'janari0-b4e82',
    databaseURL: 'https://janari0-b4e82-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'janari0-b4e82.appspot.com',
    iosClientId: '143272886853-5cf8a44j4er5hs8oh4gal4gdgme4lgik.apps.googleusercontent.com',
    iosBundleId: 'com.example.janari0Mobile',
  );
}
